### ISSUE TITLE
No auto checks

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/statusfpo#8]
Am I right that https://status.fedoraproject.org/ is a web site with no automatic checks to test the malfunctioning of the services? In other words, there is no monitoring for Fedora services that is reflected here?

**Comment by abitrolly** [comment]
I am asking because I do not see where to add additional check for failing Fedora Packages app https://github.com/fedora-infra/fedora-packages/issues/349

**Comment by rugk** [comment]
Should not this issue be named "backend is down". I'd guess that should be the prio 1 to fix that.

But yeah, proper monitoring would be good too, I guess…

**Comment by rugk** [comment]
Ahm, yes, but anyway… I want that to be fixed.

**Comment by nirik** [comment]
status.fedoraproject.org is not intended to be a automated monitoring dashboard. It's meant to list known issues so that people can look and see if a issue is known and being worked. If it's not, they can then report it or ask about it, if it is they can just keep checking status to see when the service is back and ready. 

Right now I think the status page is too complex and noisy, so I hope we can replace it with just a free form set of status updates telling people what is out/being worked on. 

We do have automated monitoring, but exposing this to end users is not very helpfull. Some service might show down, but not matter to anything, or it might cause lots of problems, it's hard to know unless you understand how all the services are interconnected. 

The packages service is currently down due to our datacenter move, and also something at least 2 people are working (on different) re-implementations of since the old one had so many problems. Check out the fedora infrastructure list for discussion about it in the last few months.

**Comment by abitrolly** [comment]
> We do have automated monitoring, but exposing this to end users is not very helpfull. 

@nirik as an end user I strongly disagree. When Travis, GitHub or Google services are down, the first thing I do is looking into their automatic status page.

I would like to keep this issue open until a consensus is reached.
